<a href="https://colab.research.google.com/github/vivekanandainduri-nv/NV/blob/main/25BDS0048_exp5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
height = [120, 122, 125, 127, 121, 123, 137, 131, 161, 145, 141, 132]
import pandas as pd
bins = [118, 125, 135, 160, 200]
category = pd.cut(height, bins)
category

[(118, 125], (118, 125], (118, 125], (125, 135], (118, 125], ..., (125, 135], (160, 200], (135, 160], (135, 160], (125, 135]]
Length: 12
Categories (4, interval[int64, right]): [(118, 125] < (125, 135] < (135, 160] < (160, 200]]

In [6]:
pd.value_counts(category)

/tmp/ipykernel_1159/1463743115.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category)

(118, 125]    5
(125, 135]    3
(135, 160]    3
(160, 200]    1
Name: count, dtype: int64

In [7]:
bin_names = ['Short Height', 'Average height', 'Good Height', 'Taller']
pd.cut(height, bins, labels=bin_names)

['Short Height', 'Short Height', 'Short Height', 'Average height', 'Short Height', ..., 'Average height', 'Taller', 'Good Height', 'Good Height', 'Average height']
Length: 12
Categories (4, object): ['Short Height' < 'Average height' < 'Good Height' < 'Taller']

In [8]:
import numpy as np
pd.cut(np.random.rand(40), 5, precision=2)

[(0.0081, 0.21], (0.6, 0.8], (0.41, 0.6], (0.0081, 0.21], (0.21, 0.41], ..., (0.21, 0.41], (0.21, 0.41], (0.21, 0.41], (0.8, 1.0], (0.21, 0.41]]
Length: 40
Categories (5, interval[float64, right]): [(0.0081, 0.21] < (0.21, 0.41] < (0.41, 0.6] < (0.6, 0.8] <
                                           (0.8, 1.0]]

In [9]:
randomNumbers = np.random.rand(2000)
category3 = pd.qcut(randomNumbers, 4)
category3

[(0.759, 1.0], (0.254, 0.51], (0.51, 0.759], (0.254, 0.51], (0.254, 0.51], ..., (-0.0009786, 0.254], (0.759, 1.0], (0.759, 1.0], (-0.0009786, 0.254], (-0.0009786, 0.254]]
Length: 2000
Categories (4, interval[float64, right]): [(-0.0009786, 0.254] < (0.254, 0.51] < (0.51, 0.759] <
                                           (0.759, 1.0]]

In [10]:
pd.value_counts(category3)

/tmp/ipykernel_1159/647498483.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category3)

(-0.0009786, 0.254]    500
(0.254, 0.51]          500
(0.51, 0.759]          500
(0.759, 1.0]           500
Name: count, dtype: int64

In [1]:
from google.colab import files
uploaded = files.upload()

Saving fraudTest.csv to fraudTest.csv

In [2]:
import pandas as pd
df = pd.read_csv("fraudTest.csv")
df.head(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0
5,5,2020-06-21 12:15:37,30407675418785,fraud_Daugherty LLC,kids_pets,19.55,Danielle,Evans,F,76752 David Lodge Apt. 064,...,42.1939,-76.7361,520,Psychotherapist,1991-10-13,798db04aaceb4febd084f1a7c404da93,1371816937,41.747157,-77.584197,0
6,6,2020-06-21 12:15:44,213180742685905,fraud_Romaguera Ltd,health_fitness,133.93,Kayla,Sutton,F,010 Weaver Land,...,40.5070,-123.9743,1139,"Therapist, occupational",1951-01-15,17003d7ce534440eadb10c4750e020e5,1371816944,41.499458,-124.888729,0
7,7,2020-06-21 12:15:50,3589289942931264,fraud_Reichel LLC,personal_care,10.37,Paula,Estrada,F,350 Stacy Glens,...,43.7557,-97.5936,343,"Development worker, international aid",1972-03-05,8be473af4f05fc6146ea55ace73e7ca2,1371816950,44.495498,-97.728453,0
8,8,2020-06-21 12:16:10,3596357274378601,"fraud_Goyette, Howell and Collier",shopping_pos,4.37,David,Everett,M,4138 David Fall,...,41.0001,-78.2357,3688,Advice worker,1973-05-27,71a1da150d1ce510193d7622e08e784e,1371816970,41.546067,-78.120238,0
9,9,2020-06-21 12:16:11,3546897637165774,fraud_Kilback Group,food_dining,66.54,Kayla,Obrien,F,7921 Robert Port Suite 343,...,31.6591,-96.8094,263,Barrister,1956-05-30,a7915132c7c4240996ba03a47f81e3bd,1371816971,31.782919,-96.366185,0

In [17]:
df = pd.read_csv("fraudTest.csv")
Amount = df["amt"]
print(Amount[np.abs(Amount)>1000])

167       1199.45
428       1881.53
951       3204.98
999       2068.05
1398      1420.90
           ...
554526    3304.44
554553    1362.77
555004    2149.66
555229    1309.21
555637    1164.37
Name: amt, Length: 1583, dtype: float64

In [18]:
outliers = df[np.abs(Amount)>1000]
print(outliers)

        Unnamed: 0 trans_date_trans_time               cc_num  \
167            167   2020-06-21 13:08:46     6011109736646996
428            428   2020-06-21 14:38:09       38530489946071
951            951   2020-06-21 17:40:54  4292743669224718067
999            999   2020-06-21 17:55:33     4933461930348832
1398          1398   2020-06-21 20:15:59  4956828990005111019
...            ...                   ...                  ...
554526      554526   2020-12-31 17:06:52     6528911529051375
554553      554553   2020-12-31 17:17:41     3582754887089201
555004      555004   2020-12-31 19:43:11     4364010865167176
555229      555229   2020-12-31 21:08:01       36913587729122
555637      555637   2020-12-31 23:30:29     6011109736646996

                                    merchant      category      amt     first  \
167                         fraud_Schumm PLC  shopping_net  1199.45   Rebecca
428                         fraud_Metz-Boehm  shopping_pos  1881.53     Laura
951        fraud_Haley, Jewess and Bechtelar  shopping_pos  3204.98   Michael
999                      fraud_Kessler Group        travel  2068.05   Richard
1398                      fraud_Kassulke PLC  shopping_net  1420.90   Kenneth
...                                      ...           ...      ...       ...
554526  fraud_Schroeder, Wolff and Hermiston        travel  3304.44     Diane
554553                       fraud_Thiel Ltd        travel  1362.77  Terrance
555004   fraud_Douglas, Schneider and Turner  shopping_pos  2149.66      Gary
555229                    fraud_Mayert Group  shopping_pos  1309.21       Ana
555637              fraud_Gleason-Macejkovic  shopping_net  1164.37   Rebecca

             last gender                             street  ...      lat  \
167      Erickson      F          594 Berry Lights Apt. 392  ...  34.2651
428         Johns      F                   95835 Garcia Rue  ...  34.9572
951      Williams      M      35822 Clayton Street Apt. 679  ...  38.2674
999        Carter      M                 5097 Martin Ridges  ...  44.9673
1398     Robinson      M                 269 Sanchez Rapids  ...  40.6747
...           ...    ...                                ...  ...      ...
554526      Smith      F       195 Murray Overpass Apt. 384  ...  45.8327
554553   Mckinney      M  42965 Christopher Fords Suite 659  ...  34.4596
555004   Martinez      M                03512 Jackson Ports  ...  39.5483
555229  Mccormick      F                4503 Patricia Route  ...  43.6498
555637   Erickson      F          594 Berry Lights Apt. 392  ...  34.2651

            long  city_pop                                   job         dob  \
167     -77.8670    186140  English as a second language teacher  1983-02-08
428     -81.9916       530                   Animal technologist  1989-05-14
951     -76.4954      5927                         Art therapist  1973-06-09
999     -93.2828   1022298                     Chemical engineer  1976-09-29
1398    -74.2239    124967                Operational researcher  1980-12-21
...          ...       ...                                   ...         ...
554526  -91.0144      1478                          Neurosurgeon  1965-04-27
554553  -93.6743      1383              Magazine features editor  1966-08-08
555004 -119.7957    276896                          Immunologist  1997-03-12
555229 -116.4306     84106                  Intelligence analyst  1971-02-11
555637  -77.8670    186140  English as a second language teacher  1983-02-08

                               trans_num   unix_time  merch_lat  merch_long  \
167     249ecb7b44d6d42a8eb155833fe23c53  1371820126  34.622777  -77.827863
428     4c4841f79d838ed6fe2c9a0f23bfbc50  1371825489  34.709044  -82.585103
951     cdb7839b9b57c1bd8f856c3166b0e9db  1371836454  37.480372  -77.349580
999     904e99f9a81c33371549da1ed53ac282  1371837333  44.444997  -93.515788
1398    6228a57f008628933ac25b0c67c7c43a  1371845759  41.030466  -74.717381
...                                  ...         ...        ...         ...
554526  c1487837b74e89b3bb62ccd678cf95a9  1388509612  45.899192  -91.504935
554553  08c57e78d6fce016f73fb3450aa55850  1388510261  35.010629  -94.389187
555004  418c90ecaebea2701d7fece2de5a4fed  1388518991  40.170913 -120.005205
555229  7a848ec13987751c1b04be6006dc360f  1388524081  42.916524 -115.787654
555637  b7f83407df7234b10f7aa2c06af06444  1388532629  34.854212  -77.711814

        is_fraud
167            0
428            0
951            0
999            0
1398           0
...          ...
554526         0
554553         0
555004         0
555229         0
555637         0

[1583 rows x 23 columns]

In [19]:

population= df["city_pop"]
print(population[np.abs(population)>500000])

21         525713
29        1577385
41        1595797
57         601723
59        2504700
           ...
555625     673342
555633    1312922
555649    1526206
555664    1577385
555680    1577385
Name: city_pop, Length: 28028, dtype: int64

In [20]:
clean_df = df[df["amt"]<=1000]
print(clean_df.shape)
clean_df.to_csv("clean_data.csv",index = False)

(554136, 23)

In [11]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [12]:
data = {
 'Age': [25, 30, 45, 35, 22],
 'Salary': [50000, 64000, 120000, 85000, 1200000] # 1,200,000 is an outlier
}
df = pd.DataFrame(data)
print("Original Data:\n", df, "\n")

Original Data:
    Age   Salary
0   25    50000
1   30    64000
2   45   120000
3   35    85000
4   22  1200000

In [13]:
min_max_scaler = MinMaxScaler()
df_min_max = pd.DataFrame(
 min_max_scaler.fit_transform(df),
 columns=df.columns
)
print("Min-Max Scaled Data:\n", df_min_max, "\n")

Min-Max Scaled Data:
         Age    Salary
0  0.130435  0.000000
1  0.347826  0.012174
2  1.000000  0.060870
3  0.565217  0.030435
4  0.000000  1.000000

In [14]:
standard_scaler = StandardScaler()
df_standard = pd.DataFrame(
 standard_scaler.fit_transform(df),
 columns=df.columns
)
print("Standardized Data:\n", df_standard, "\n")

Standardized Data:
         Age    Salary
0 -0.788742 -0.565609
1 -0.172537 -0.534409
2  1.676077 -0.409609
3  0.443667 -0.487609
4 -1.158465  1.997236